// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	big "math/big"

	mock "github.com/stretchr/testify/mock"
)

// S3Client is an autogenerated mock type for the S3Client type
type S3Client struct {
	mock.Mock
}

// getBlock provides a mock function with given fields: blockNumber
func (_m *S3Client) GetBlock(blockNumber *big.Int) (string, error) {
	ret := _m.Called(blockNumber)

	var r0 string
	if rf, ok := ret.Get(0).(func(*big.Int) string); ok {
		r0 = rf(blockNumber)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*big.Int) error); ok {
		r1 = rf(blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storeBlock provides a mock function with given fields: blockNumber, data
func (_m *S3Client) StoreBlock(blockNumber *big.Int, data string) error {
	ret := _m.Called(blockNumber, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*big.Int, string) error); ok {
		r0 = rf(blockNumber, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
