// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	big "math/big"

	types "github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
)

// s3Client is an autogenerated mock type for the s3Client type
type s3Client struct {
	mock.Mock
}

// getBlock provides a mock function with given fields: blockNumber
func (_m *s3Client) getBlock(blockNumber *big.Int) (*types.Block, error) {
	ret := _m.Called(blockNumber)

	var r0 *types.Block
	if rf, ok := ret.Get(0).(func(*big.Int) *types.Block); ok {
		r0 = rf(blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*big.Int) error); ok {
		r1 = rf(blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// storeBlock provides a mock function with given fields: block
func (_m *s3Client) storeBlock(block *types.Block) error {
	ret := _m.Called(block)

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Block) error); ok {
		r0 = rf(block)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
