// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	types "github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
)

// snsClient is an autogenerated mock type for the snsClient type
type snsClient struct {
	mock.Mock
}

// broadcast provides a mock function with given fields: block
func (_m *snsClient) broadcast(block *types.Block) error {
	ret := _m.Called(block)

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Block) error); ok {
		r0 = rf(block)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
